services:
  my_app_1:
    image: "097656145156.dkr.ecr.us-east-1.amazonaws.com/web_app:v1"
    ports:
      - "8081:8080"  # Exposing different ports for each instance
    environment:
      - DBHOST=my_db_net  # Custom alias for my_db
      - DBPORT=3306
      - DBPWD=123456789
      - APP_COLOR=red  # Unique APP_COLOR
    depends_on:
      - my_db
    restart: always
    networks:
      - network1

  my_app_2:
    image: "097656145156.dkr.ecr.us-east-1.amazonaws.com/web_app:v1"
    ports:
      - "8082:8080"
    environment:
      - DBHOST=my_db_net
      - DBPORT=3306
      - DBPWD=123456789
      - APP_COLOR=green
    depends_on:
      - my_db
    restart: always
    networks:
      - network1

  my_app_3:
    image: "097656145156.dkr.ecr.us-east-1.amazonaws.com/web_app:v1"
    ports:
      - "8083:8080"
    environment:
      - DBHOST=my_db_net
      - DBPORT=3306
      - DBPWD=123456789
      - APP_COLOR=blue
    depends_on:
      - my_db
    restart: always
    networks:
      - network1

  my_db:
    image: "097656145156.dkr.ecr.us-east-1.amazonaws.com/dbs_app:v1"
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
    volumes:
      - db_data:/data/db
    restart: always
    networks:
      network1:
        aliases:
          - my_db_net  # Alias for my_db

volumes:
  db_data:

networks:
  network1:  # This was missing in your original code
    name: my_chosen_network  # Optional: You can give your network a specific name

