name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
            
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Test AWS Credentials
        run: |
          echo "Running AWS sts get-caller-identity"
          aws sts get-caller-identity --debug
          echo "Describing ECR repositories"
          aws ecr describe-repositories --region ${{ secrets.AWS_REGION }} --debug

      - name: Login to Amazon ECR
        run: |
          echo "Logging in to ECR"
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com || exit 1

      - name: Build Docker Images
        run: |
          echo "Building webapp image"
          docker build -t webapp-image -f Dockerfile .
          echo "Building mysql image"
          docker build -t mysql-image -f Dockerfile_mysql .

      - name: Tag and Push to Amazon ECR
        run: |
          echo "Tagging webapp image"
          docker tag webapp-image:latest ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/webapp-image:latest
          echo "Tagging mysql image"
          docker tag mysql-image:latest ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mysql-image:latest
          echo "Pushing webapp image to ECR"
          docker push ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/webapp-image:latest
          echo "Pushing mysql image to ECR"
          docker push ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mysql-image:latest
